#
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Go.gitlab-ci.yml

image: golang:latest

stages:
  - test
  - build
  - deploy

format:
  stage: test
  script:
    - go fmt $(go list ./... | grep -v /vendor/)
    - go vet $(go list ./... | grep -v /vendor/)
    - go test -race $(go list ./... | grep -v /vendor/)

compile:
  stage: build
  script:
    - mkdir -p ${CI_PROJECT_NAME}
    - go build -o ${CI_PROJECT_NAME} ./...
  artifacts:
    paths:
      - ${CI_PROJECT_NAME}

deploy:
  stage: deploy
  script: echo "Define your deployment script!"
  environment: production

default:
  tags:
    - terraform
